version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AIRI
  - alaya
  - alint
  - antfu
  - apalis
  - apeira
  - Balatro
  - bbox
  - bufbuild
  - bumpp
  - BYOA
  - clippy
  - conv
  - cust
  - decimalturn
  - direnv
  - dotenv
  - evals
  - fsrs
  - graphiti
  - guiiai
  - haru
  - hnsw
  - iden
  - insel
  - Kerbal
  - Kimi
  - kwaa
  - KWWK
  - libgbm
  - libglvnd
  - libiconv
  - libxcb
  - libxkbcommon
  - locomo
  - Logg
  - mediaremote
  - moeru
  - msvc
  - nemori
  - netease
  - nixpkgs
  - nolyfill
  - ollama
  - oper
  - oxlint
  - paradedb
  - pgvector
  - picospinner
  - pkgs
  - pkill
  - plast
  - plastmem
  - pname
  - prefs
  - prost
  - protoc
  - qodana
  - qqmusic
  - qwen
  - retrievability
  - rustc
  - rustls
  - schemars
  - seaql
  - serde
  - sonarjs
  - sqlx
  - stdenv
  - swiftc
  - taze
  - tesseract
  - tinyexec
  - tutils
  - ultralytics
  - unocss
  - unrun
  - utoipa
  - uuidv
  - vchord
  - vite
  - vitejs
  - vitest
  - waifu
  - xiaowu
  - xorg
  - xsai
ignoreWords: []
import: []
